# docker compose file for rcpch.tech

services:
  mkdocs:
    build: .
    volumes:
      - .:/app/
    ports:
      - 8022:8000
    environment:
      - ENABLE_GIT_COMMITTERS=False # Disables git committer extension in local dev
      - ENABLE_PDF_EXPORT=0 # Disables automatic PDF generation in local dev
    command: mkdocs serve --config-file mkdocs.yml
    restart: always
