version: "3.11" # Docker Compose specification version! NOT the Python version

services:
  mkdocs:
    build: .
    volumes:
      - .:/app/
    ports:
      - 8001:8001
    environment:
      - ENABLE_GIT_COMMITTERS=False # Disables git committer extension in local dev
      - ENABLE_PDF_EXPORT=0 # Disables automatic PDF generation in local dev
    command: mkdocs serve --config-file mkdocs.yml
    restart: always
